# List 2 dimensi

In [1]:
#list 2 dimensi yaitu menenmpatkan list di dalam list
#untuk list sendiri menggunakan "[]"
matrix = [
    [1,3,5],
    [8,9,10],
    [12,14,16]
]
print (matrix)

#memanggil matrix pada index
#contoh I
#memanggil matrix pada index ke - 0
matrix [0]
print (matrix [0])
#contoh II
#memanggil matrix pada index ke - -1 atau ke - 2
matrix [-1]
print (matrix[-1])

#memanggil matrix pada baris dan kolom tertentu
#contoh I
#memanggil matrix pada baris ke - 1 kolom ke -1
matrix [1][1]
print (matrix [1][1])
#contoh II
#memanggil matrix pada baris terakhir kolom ke - 0
matrix [-1][0]
print (matrix[-1][0])

[[1, 3, 5], [8, 9, 10], [12, 14, 16]]
[1, 3, 5]
[12, 14, 16]
9
12


In [3]:
#merubah nilai matrix pada baris dan kolom tertentu
#contoh I
#merubah nilai matrix pada baris ke - 2 kolom ke -1
matrix [2][1] = 15
print (matrix [2][1])
#contoh II
#merubah nilai matrix pada baris dan kolom terakhir 
matrix [-1][-1] = 17
print (matrix [-1][-1])

#memanggil seluruh list di dalam list
print (matrix)
#maka saat dipanggil nilai yang tadi dirubah akan menggantikan nilai sebelumnya
for objek in matrix :
    print (objek)
#atau kita dapat menggunakan for untuk memnaggil semua list
#namun ada sedikit perbedaan pada output
#jika kita menggunakan "print (matrix)" maka outputnya adalah "list didalam list",
#sedangkan bila kita gunakan for maka output yang muncul "hanya list" yang berada di dalam list

15
17
[[1, 3, 5], [8, 9, 10], [12, 15, 17]]
[1, 3, 5]
[8, 9, 10]
[12, 15, 17]


# Tuples

In [3]:
#hampir mirip seperti list hanya saja nilai tuples tidak dapat dirubah (tetap),
#sedangkan nilai list dapat dirubah (tidak tetap)
#untuk tupples biasanya menggunakan "()"
nama_anggota = ('A', 'N', 'Y')
print (nama_anggota)

#memanggil index tertentu
#contoh I 
#memanggil index ke 0
nama_anggota [0]
print (nama_anggota [0])
#contoh II
#memanggil index ke terakhir
nama_anggota [-1]
print (nama_anggota [-1])

#memanggil index dengan urutan tertentu
#contoh I
#misalnya kita ingin memanggil index ke - 0 sampai ke terakhir
print (nama_anggota [0:3])
#contoh II
#misalnya kita ingin memanggil index namun dengan urutan yang dilompati 2
print (nama_anggota [0::2])

#memanggil seluruh list
print (nama_anggota)
#atau kita juga dapat menggunakan for untuk memanggil seluruh list
for pasangan in nama_anggota:
    print (pasangan)

('A', 'N', 'Y')
A
Y
('A', 'N', 'Y')
('A', 'Y')
('A', 'N', 'Y')
A
N
Y


In [5]:
#melakukan perubahan pada tuples
#contoh I
#ingin merubah "y"
nama_anggota [2] = "E"
#maka akan menampilkan eror karena "Y" sendiri tidak bisa digantikan oleh apapun karena ia bersifat tupples
#contoh II
nama_anggota.append ("Al")
#contoh III
nama_anggota.remove ("Y")
#karena semua yang dijalankan mengalami eror
#maka dapat disimpulkan tupple sendiri tidak dapat dirubah nilainya baik itu ditambahkan atau dihilangkan

TypeError: 'tuple' object does not support item assignment

In [8]:
#menghitung banyaknya elemen yang muncul pada index
nama_anggota.count ('A')
#karena untuk index "A" hanya sekali muncul 
#maka outoputnya adalah 1

1

# Dictionaries

In [9]:
#digunakan apabila data nya terkait satu sama lain
#untuk dictionarie biasanya menggunakan "{ }"
data_kelompok = {
    "Nama Ketua" : "A",
    "Nama Sekretaris" : "Y",
    "Nama Anggota" : ["Jaya", "Pathur", "Bang DO"]
}
print (data_kelompok)

{'Nama Ketua': 'A', 'Nama Sekretaris': 'Y', 'Nama Anggota': ['Jaya', 'Pathur', 'Bang DO']}


In [10]:
#memanggil data dari dictionaries
#contoh I
print (data_kelompok["Nama Ketua"])
#contoh II
print (data_kelompok["nama ketua"])
#akan mengalami eror karena harus sesuai dengan isi pada dictionaries
#contoh III
#memanggil data yang tidak ada pada dictionaries
print (data_kelompok["Nama Bendahara"])
#maka syntax akan mengalami eror

A


KeyError: 'nama ketua'

In [12]:
#memanggil data dari dictionaries menggunakan "get"
#contoh I
print (data_kelompok.get("Nama Sekretaris"))
#contoh II
print (data_kelompok.get("Nama Anggota"))
#contoh III
print (data_kelompok.get("Nama Bendahara"))
#none
#karena tidak ada dalam dictionaries
#contoh IV
print (data_kelompok.get("Nama Bendahara", "Nama Wakil ketua"))
#maka data hanya akan membaca data selanjutnya
#contoh V
print (data_kelompok.get("Nama Bendahara", "02-10-2003"))

Y
['Jaya', 'Pathur', 'Bang DO']
None
Nama Wakil ketua
02-10-2003


In [13]:
#memanggil dictionaries menggunakan for
for nama in data_kelompok:
    print (nama)

Nama Ketua
Nama Sekretaris
Nama Anggota


In [14]:
#menambahkan data pada dictionaries
data_kelompok ["Nama Kelompok"] = "Hilmi Squad"
print (data_kelompok["Nama Kelompok"])

Hilmi Squad


In [15]:
#menampilkan data yang telah diperbarui
print(data_kelompok)

{'Nama Ketua': 'A', 'Nama Sekretaris': 'Y', 'Nama Anggota': ['Jaya', 'Pathur', 'Bang DO'], 'Nama Kelompok': 'Hilmi Squad'}


In [19]:
#menggunakan dictionaries untuk memasuki angka
angka = {
    "0" : "kosong",
    "1" : "satu",
    "2" : "dua",
    "3" : "tiga",
    "4" : "empat",
    "5" : "lima",
    "6" : "enam",
    "7" : "tujuh",
    "8" : "delapan",
    "9" : "sembilan",
}

In [20]:
NIM = input ("Masukkan NIM Anda ")
#menggunakan ""
nomor_angka = ""
#menyimpan nilai dari proses perulangan
for nilai in NIM:
    nomor_angka += angka.get(nilai) + " "
    #nomor_angka = nomor angka + angka.get + spasi
print (nomor_angka)

Masukkan NIM Anda 2208541040
dua dua kosong delapan lima empat satu kosong empat kosong 


In [21]:
NIM = input ("Masukkan NIM Anda ")
#menggunakan str ()
nomor_angka = str ()
#menyimpan nilai dari proses perulangan
for nilai in NIM:
    nomor_angka += angka.get(nilai) + " "
    #nomor_angka = nomor angka + angka.get + spasi
print (nomor_angka)

Masukkan NIM Anda 2208541018
dua dua kosong delapan lima empat satu kosong satu delapan 


# Fungsi dalam Python

In [23]:
#def digunakan untuk mendefinisikan suatu fungsi
def full_nama(nama_depan,nama_belakang):
    print (f"nama lenkapnya adalah {nama_depan} {nama_belakang}")

In [24]:
nama_depan = input ("masukkan nama depan ")
nama_belakang = input ("masukkan nama belakang ")
full_nama (nama_depan,nama_belakang)

masukkan nama depan andika
masukkan nama belakang pandya
nama lenkapnya adalah andika pandya


In [25]:
#menggunakan library numpy
import numpy as np

In [26]:
#menghitung luas bangun datar
#contoh I mengitung luas segitiga
def luas_segitiga(alas, tinggi):
    luas = 1/2 * alas * tinggi
    return luas
#maka eksekusi fungsi berhenti 

In [27]:
alas = int (input ("masukkan nilai alas "))
tinggi = int (input ("masukkan nilai tinggi "))
luas_segitiga(alas, tinggi)

masukkan nilai alas 4
masukkan nilai tinggi 10


20.0

In [28]:
#contoh II menghitung luas lingkaran
def luas_lingkaran(jari_jari):
    luas = np.pi * jari_jari**2
    return luas

In [29]:
jari_jari = int (input ("masukkan nilai jari_jari "))
luas_lingkaran(jari_jari)

masukkan nilai jari_jari 7


153.93804002589985

In [30]:
#menghitung volume bangun ruang prisma
def volume_prisma(luas_alas,tinggi_prisma):
    volume = luas_alas * tinggi_prisma
    return volume
#eksekusi fungsi berhenti disini

In [31]:
luas_alas = input ("bentuk luas alas = ")
#if kondisi : aksi
if luas_alas == "segitiga":
#jika segitiga jalankan ini
    alas_segitiga = input ("alas = ")
    tinggi_segitiga = input ("tinggi segitiga = ")
    luas_alas = 1/2 * (int (alas_segitiga) * int (tinggi_segitiga)) 
    print (luas_alas)
elif luas_alas == "segi empat":
#jika segi empat jalankan ini
    panjang = input ("panjang = ")
    lebar = input ("lebar = ")
    luas_alas = (int (panjang) * int (lebar))
    print (luas_alas)
tinggi_prisma = int (input ("tinggi prisma = "))
volume_prisma (luas_alas,tinggi_prisma)
#mewadahkan fungsi volume_prisma
volume = volume_prisma (luas_alas,tinggi_prisma)
print (f"volume prisma adalah {volume}")

bentuk luas alas = segitiga
alas = 4
tinggi segitiga = 7
14.0
tinggi prisma = 15
volume prisma adalah 210.0


# Numpy

In [32]:
#numpy adalah library dalam python yang memiliki keunggulan dalam perhitungan vektor dan matrix
#memanggil numpy
a = np.array ([0,1,2,3,4])
#array = kumpulan variabel yang menyimpan data dengan tipe yang sama
print (a)

[0 1 2 3 4]


In [33]:
b = np.array ([[5,7,9,11], [6,8,10,12]])
print (b)

[[ 5  7  9 11]
 [ 6  8 10 12]]


In [34]:
c = np.array ([[1,2,3,4],[5,7,9,11],
               [2,5,4,2],[9,0,3,1]])
print (c)

[[ 1  2  3  4]
 [ 5  7  9 11]
 [ 2  5  4  2]
 [ 9  0  3  1]]


In [35]:
a.ndim

1

In [36]:
b.ndim

2

In [37]:
c.ndim

2

In [38]:
#shape = (baris,kolom)
a.shape

(5,)

In [39]:
b.shape

(2, 4)

In [40]:
c.shape

(4, 4)

### Memanggil Anggota Kolom dan Baris dengan Numpy

In [41]:
c = np.array ([[1,2,3,4],[5,7,9,11],
               [2,5,4,2],[9,0,3,1]])
print (c)

[[ 1  2  3  4]
 [ 5  7  9 11]
 [ 2  5  4  2]
 [ 9  0  3  1]]


In [42]:
#contoh I 
#memanggil baris 0 kolom 0
c[0,0]

1

In [43]:
#contoh II
#memanggil dari baris 0 sampai kolom terakhir
c[0,:]

array([1, 2, 3, 4])

In [44]:
#contoh III
#memanggil dari baris terakhir sampai kolom terakhir
c[-1,:]

array([9, 0, 3, 1])

In [45]:
#contoh IV
#memanggil dari kolom 0 sampai baris terakhir
c[:,0]

array([1, 5, 2, 9])

In [46]:
#memanggil kolom dan baris dengan batasan
#contoh I
#memanggil baris 2 kolom 1 dengan batas sampai 4
c[2,1:4]

array([5, 4, 2])

In [47]:
#contoh II
#memanggil baris 2 kolom 1 dengan batas sampai 3
c[2,1:3]

array([5, 4])

In [48]:
#mengganti baris dan kolom
#misalnya mengganti nilai pada baris ke - 3 kolom ke - 2
c[3,2]=10
print (c)

[[ 1  2  3  4]
 [ 5  7  9 11]
 [ 2  5  4  2]
 [ 9  0 10  1]]


## Matrix pada Numpy

In [49]:
#perintah pada matrix
#matrix 3x2 dengan nilai 0
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [50]:
#matrix 2x2 dengan nilai 1
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [51]:
#matrix identitas 4x4
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [55]:
#membuat 2 matrix dengan nilai baris dan kolom yang sama
np.ones((2,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [56]:
#membuat matrix 3 X 3 dengan semua nilai 0
np.full((3,3),0)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [58]:
#membuat matrix dengan nilai acak dengan ukuran 4 X 3
np.random.rand(4,3)

array([[0.17007433, 0.60306552, 0.22880252],
       [0.75395154, 0.86154693, 0.17477307],
       [0.4049708 , 0.60838811, 0.07114695],
       [0.72020172, 0.46871743, 0.68618764]])

In [59]:
#membuat matrix dengan nilai acak mulai dari rentang 1-10 dengan ukuran 4 X 3
np.random.randint(1,10,size=(4,3))

array([[2, 1, 8],
       [8, 4, 5],
       [8, 4, 8],
       [7, 5, 1]])

In [63]:
#membuat matrix 0 dengan ukuran 5 X 5
a = np.zeros ((5,5))
print (a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [67]:
c = 9*b
print (c)

[[ 45  63  81  99]
 [ 54  72  90 108]]


In [71]:
#matrix 3x3 dengan  nilai 1
d = np.ones ((3,3))
#matrix identitas 3x3 dengan diagonal utama 3 
e = np.identity (3)*3
f = d+e
print (f)

[[4. 1. 1.]
 [1. 4. 1.]
 [1. 1. 4.]]


In [74]:
#matrix 4x4 dengan nilai 1 x 2
x = np.ones((4,4))*2
#matrix identitas 4x4 dengan diagonal utama 7
y = np.identity (4)*7
z = x + y
print(z)

[[9. 2. 2. 2.]
 [2. 9. 2. 2.]
 [2. 2. 9. 2.]
 [2. 2. 2. 9.]]


## Copy pada Numpy

In [75]:
a = np.array ([2,3,5,6,7])
print (a)

[2 3 5 6 7]


In [76]:
#mengopy wadah a ke b
#maka a = b
b = a
print (b)

[2 3 5 6 7]


In [81]:
#mengganti baris ke 0 kolom ke 3
b[3] =9
print (b)
#bila kita sudah dapat mengganti nilai dan kita menghapus ulang, ingin mengganti yang baru
#maka nilai yang sudah dihapus sebelumnya itu masih tetap ada
#contoh 
#untuk b[0] = 10

[10  3  5  9  7]


In [83]:
#parameter asli ikut terpengaruh
print (a)

[10  3  5  9  7]


In [84]:
c = np.array ([2,3,4,5,6])
print (c)

[2 3 4 5 6]


In [85]:
#menngunakan fungsi "copy ()"
d = c.copy ()
print (d)

[2 3 4 5 6]


In [86]:
d[2] = 100
print (d)

[  2   3 100   5   6]


In [87]:
#hasil yang telah dirubah ternyata tidak berpengaruh pada parameter aslinya
print (c)

[2 3 4 5 6]


## Operasi Matematika pada Numpy

In [88]:
#contoh I pertambahan
x = a + 2
print (x)
#akan menambahkan nilai pada "a sebelumnya yaitu : (10,3,5,9,7)"
#contoh II pengurangan
x = c - 2
print (x)
#mengurangi nilai pada "c sebelumnya yaitu (2,3,4,5,6)"
#contoh III perkalian
x = d*1
print (x)
#mengalikan nilai pada "d sebelumnya yaitu (2,3,100,5,6)"
#contoh IV pembagian
x = b/2
print (x)
#membagi nilai pada "b sebelumnya yaitu (10,3,5,9,7)"
#contoh V pemangkatan
#menjalankan tanpa perlu di wadahkan
a**2
#akan memangkatkan nilai pada "a sebelumnya yaitu : (10,3,5,9,7)"

[12  5  7 11  9]
[0 1 2 3 4]
[  2   3 100   5   6]
[5.  1.5 2.5 4.5 3.5]


array([100,   9,  25,  81,  49], dtype=int32)

In [89]:
print (a)

[10  3  5  9  7]


In [90]:
np.cos (a)

array([-0.83907153, -0.9899925 ,  0.28366219, -0.91113026,  0.75390225])

In [91]:
np.tan (a)

array([ 0.64836083, -0.14254654, -3.38051501, -0.45231566,  0.87144798])

In [92]:
#sinus hiperbolik
np.sinh (a)

array([1.10132329e+04, 1.00178749e+01, 7.42032106e+01, 4.05154190e+03,
       5.48316123e+02])

In [93]:
#cosinus hiperbolik
np.cosh (a)

array([1.10132329e+04, 1.00676620e+01, 7.42099485e+01, 4.05154203e+03,
       5.48317035e+02])

In [94]:
#tangen hiperbolik
np.tanh (a)

array([1.        , 0.99505475, 0.9999092 , 0.99999997, 0.99999834])

In [95]:
#akar kuadrat
np.sqrt (a)

array([3.16227766, 1.73205081, 2.23606798, 3.        , 2.64575131])

## Perkalian Matrix pada Numpy

In [102]:
#contoh I
#perkalian matrix 3 x 3
a = np.array ([[1,2,1],[2,1,5],[3,0,2]])
print (a)

[[1 2 1]
 [2 1 5]
 [3 0 2]]


In [103]:
b = np.array ([[2,4,3],[3,5,7],[0,1,3]])
print (b)

[[2 4 3]
 [3 5 7]
 [0 1 3]]


In [104]:
c = a*b
print (c)

[[ 2  8  3]
 [ 6  5 35]
 [ 0  0  6]]


In [118]:
#menjalankan perintah matmul
d = np.matmul(a,b)
print (d)

[[26 38]
 [58 40]]


In [119]:
#contoh II
#perkalian matrix 2 x 3 dan 3 x 2
a = np.array ([[7,2,4],[2,9,5]])
print (a)

[[7 2 4]
 [2 9 5]]


In [120]:
b = np.array ([[2,4],[3,5],[2,1]])
print (b)

[[2 4]
 [3 5]
 [2 1]]


In [121]:
c = a*b
print (c)
#syntax eror karena memiliki jumlah baris dan kolom yang berbeda

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [122]:
#contoh III
#perkalian matrix 2 x 3 dan 3 x 4
a = np.array ([[7,2,4],[2,9,5]])
print (a)

[[7 2 4]
 [2 9 5]]


In [123]:
b = np.array ([[2,4,3,4],[6,3,5,7],[1,0,1,3]])
print (b)

[[2 4 3 4]
 [6 3 5 7]
 [1 0 1 3]]


In [124]:
c = a*b
#syntax eror karena memiliki jumlah baris dan kolom yang berbeda

ValueError: operands could not be broadcast together with shapes (2,3) (3,4) 

In [125]:
#contoh IV
#menjalnkan matmul dengan matrix 2 x 3 dan 3 x 2
a = np.array ([[7,2,4],[2,9,5]])
print (a)

[[7 2 4]
 [2 9 5]]


In [126]:
b = np.array ([[2,4],[6,3],[0,1]])
print (b)

[[2 4]
 [6 3]
 [0 1]]


In [127]:
c = np.matmul(a,b)
print (c)

[[26 38]
 [58 40]]


In [128]:
#contoh V
#menjalankan matmul dengan matrix 2 x 3
a = np.array ([[7,2,4],[2,9,5]])
print (a)
b = np.array ([[2,4,0],[6,1,3]])
print (b)

[[7 2 4]
 [2 9 5]]
[[2 4 0]
 [6 1 3]]


In [129]:
c = np.matmul (a,b)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

## Min, Max, dan Sum pada Numpy

In [130]:
a = np.array ([[1,2,1],[2,1,5],[3,0,2]])
print (a)

[[1 2 1]
 [2 1 5]
 [3 0 2]]


In [131]:
#min pada matrix yang di wadahkan pada a
b = np.min(a)
print (b)

0


In [132]:
#max pada matrix yang di wadahkan pada a
c = np.max(a)
print (c)

5


In [133]:
#axis = 0 untuk np.min
#agregasi = penyusun
d = np.min(a,axis=0)
#axis=0 menunjukkan agregasi di sepanjang baris
print (d)
#axis = 0 untuk np.max
e = np.max(a,axis=0)
print (e)

[1 0 1]
[3 2 5]


In [134]:
#axis = 1 untuk np.min
f = np.min(a,axis=1)
#axis=1 menunjukkan agregasi di sepanjang kolom
print (d)
#axis = 1 untuk np.max
g = np.max(a,axis=1)
print (g)

[1 0 1]
[2 5 3]


In [135]:
#sum pada matrix di wadah a
h = np.sum(a)
print (h)

17


In [136]:
#axis = 0 untuk np.sum
i = np.sum(a,axis=0)
#axis=0 menunjukkan agregasi di sepanjang baris
print (i)
#axis = 1 untuk np.sum
j = np.sum(a,axis=1)
#axis=1 menunjukkan agregasi di sepanjang kolom
print (j)

[6 3 8]
[4 8 5]
